config/routes.rb
Rails.application.routes.draw do
  resource :dashboard

  resources :posts do
    collection do
      get 'popular'
    end

    member do
      post 'like' 
      post 'email'
    end
  end

  devise_for :users

  root to: 'posts#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/contestable.rb
module Contestable
  extend ActiveSupport::Concern

  def calculate_popularity
    self.popularity = self.likes.count + (self.email_signups.count * 2)
    self.save
  end

  module ClassMethods
    def by_likes
      self.left_joins(:likes)
          .group(:id).select('posts.*', 'COUNT(likes.id) like_count')
          .order(like_count: :desc)
    end

    def by_popularity
      self.order(popularity: :desc)
    end

    def reap_the_uncools
      self.where('created_at < ?', DateTime.now - 30.days)
          .update_all(popularity: 0)
    end
  end
end

app/models/email_signup.rb
class EmailSignup < ApplicationRecord
  belongs_to :post
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  include Contestable

  belongs_to :user
  has_one_attached :image
  has_many :email_signups
  has_many :likes

  paginates_per 60

  # Allow simple_form to use params[:post][:email] for email signups
  attr_accessor :email  
end

app/models/user.rb
class User < ApplicationRecord
  paginates_per 100

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
  has_many :email_signups, through: :posts
  has_many :likes, through: :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController

  def show
    @users = User.all.page params[:page]
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :destroy, :edit, :like, :new, :update]
  before_action :set_post, only: [:show, :edit, :email, :like, :update, :destroy]

  def like
    # Only one like per user, please
    unless Like.where(post_id: @post.id, user_id: current_user.id).first
      Like.create(post_id: @post.id, user_id: current_user.id)
    end

    redirect_back fallback_location: @post
  end

  def email
    # No need to collect the same email address more than once
    unless EmailSignup.where(email: params[:post][:email]).first
      EmailSignup.create(email: params[:post][:email], post_id: @post.id)
    end

    redirect_to @post
  end

  def popular
    @posts = Post.by_popularity.page params[:page]

    # respond_to do |format|
    #   format.html { render :index }
    # end
  end

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.order(created_at: :desc).page params[:page]
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:description, :email, :image, :page)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/dashboards/show.html.haml
%h1 Dashboard

%table.table
  %thead
    %tr
      %th User
      %th Likes
      %th Signups

  %tbody
    - @users.each do |user|
      %tr
        %td= "@" + user.username
        %td= user.likes.count
        %td= user.email_signups.count

%p
  = link_to_next_page(@users, 'Next Page')

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-expand-md.navbar-light.bg-light
  .container
    %a.navbar-brand{href: "/"} GRAMCRACKER
    %button.navbar-toggler{"aria-controls" => "navbarsExampleDefault", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarsExampleDefault", "data-toggle" => "collapse", type: "button"}
      %span.navbar-toggler-icon
    #navbarsExampleDefault.collapse.navbar-collapse
      %ul.navbar-nav.mr-auto
        %li.nav-item
          %a.nav-link{href: "/posts"} POSTS
        %li.nav-item
          %a.nav-link{href: "/posts/popular"} POPULAR
        %li.nav-item
          %a.nav-link{href: "/dashboard"} DASHBOARD
        %li.nav-item
          %a.nav-link{href: "/posts/new", class: "text-danger"} CREATE

app/views/layouts/application.html.haml
!!!
%html{lang: "en"}
  %head
    = csrf_meta_tags
    = csp_meta_tag
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{charset: "utf-8"}/
    %meta{content: "width=device-width, initial-scale=1, shrink-to-fit=no", name: "viewport"}/
    %meta{content: "", name: "Gramcracker"}/
    %link{href: "../../../../favicon.ico", rel: "icon"}/
    %title Gramcracker
    = stylesheet_link_tag "application"
  %body
    = render "layouts/navbar"
    .container
      .yield-container
        = yield
    %footer.footer
      .container
        %span
          COPYRIGHT &#169;
          = CURRENT_YEAR
          GRAMCRACKER, INC
    = javascript_include_tag "application"

app/views/posts/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@post) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.file_field :image
    = f.input :description

  .form-actions
    = f.button :submit

app/views/posts/_post.html.haml
.card.mb3{:style => "max-width: 420px;"}
  .card-body
    %p.card-title
      = "@" + post.user.username
    = link_to image_tag(post.image.variant(resize_to_limit: [400, 400]), :class => "card-img-top"), post_path(post)
    %p.card-text
      = post.description
    %p
      = button_to 'Like', like_post_path(post)
    %p
      %b= post.likes.count
      likes

app/views/posts/edit.html.haml
%h1 Editing post

= render 'form'

= link_to 'Show', @post
\|
= link_to 'Back', posts_path

app/views/posts/index.html.haml
.posts
  = render @posts

.pagination
  = link_to_next_page(@posts, 'Next Page', remote: true)

app/views/posts/index.js.erb
// Append new data
$("<%=j render(@posts) %>")
  .appendTo($(".posts"));

// Update pagination link
<% if @posts.last_page? %>
  $('.pagination').html("That's all, folks!");
<% else %>
  $('.pagination')
    .html("<%=j link_to_next_page(@posts, 'Next Page', :remote => true) %>");
<% end %>

app/views/posts/new.html.haml
%h1 New post

= render 'form'

= link_to 'Back', posts_path

app/views/posts/popular.html.haml
.posts
  = render @posts

.pagination
  = link_to_next_page(@posts, 'Next Page', remote: true)

app/views/posts/popular.js.erb
// Append new data
$("<%=j render(@posts) %>")
  .appendTo($(".posts"));

// Update pagination link
<% if @posts.last_page? %>
  $('.pagination').html("That's all, folks!");
<% else %>
  $('.pagination')
    .html("<%=j link_to_next_page(@posts, 'Next Page', :remote => true) %>");
<% end %>

app/views/posts/show.html.haml
%p#notice= notice

.card.mb3{:style => "max-width: 420px;"}
  .card-body
    %p
      = "@" + @post.user.username
    %p
      = image_tag @post.image.variant(resize_to_limit: [400, 400])
    %p
      = button_to 'Like', like_post_path(@post)
    %p
      %b= @post.likes.count
      likes
    %p
      = @post.description
    %p
      %b Join the Gramcracker email list here!
      = simple_form_for(@post, method: :post, url: email_post_path) do |f|

        .form-inputs
          = f.input :email, label: false

        .form-actions
          = f.submit 'Submit'